# Generated by Django 5.1.1 on 2024-10-26 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichapac', '0007_alter_historiaclinica_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='fichapac.paciente'),
        ),
    ]
